accounts/views/login/forms.py
# -*- coding: utf-8 -*-
from flask.ext.wtf import Form
from wtforms import TextField, PasswordField, validators


class LoginForm(Form):
    username = TextField(u'Benutzername')
    password = PasswordField('Passwort', [validators.Required()])

accounts/__init__.py
# -*- coding: utf-8 -*-
import os
from flask import Flask, g, session

from models import Service
from utils import get_backend
from utils.confirmation import Confirmation
from utils.sessions import EncryptedSessionInterface
from utils.login import create_login_manager
from views import default, login, admin


def absolute_paths(app, config):
    def handle_option(dirname, name):
        if app.config.get(name):
            app.config[name] = os.path.join(dirname, app.config[name])

    dirname = os.path.dirname(config)
    handle_option(dirname, 'USERNAME_BLACKLIST_FILE')


def load_config(app, configfile):
    if configfile is not None:
        filename = os.path.abspath(configfile)
        app.config.from_pyfile(filename)
        absolute_paths(app, filename)


def create_app(config=None):
    app = Flask(__name__)
    app.config.from_object('accounts.default_settings')
    load_config(app, os.environ.get('SPLINE_ACCOUNT_WEB_SETTINGS'))
    load_config(app, config)

    app.register_blueprint(default.bp)
    app.register_blueprint(login.bp)
    app.register_blueprint(admin.bp, url_prefix='/admin')
    app.session_interface = EncryptedSessionInterface()

    app.all_services = list()
    for (name, url) in app.config.get('SERVICES', list()):
        cn = name.lower()
        app.all_services.append(Service(cn, name, url))

    app.username_blacklist = list()
    if app.config.get('USERNAME_BLACKLIST_FILE'):
        with open(app.config['USERNAME_BLACKLIST_FILE']) as f:
            app.username_blacklist = [line.rstrip() for line in f]

    login_manager = create_login_manager()
    login_manager.init_app(app)

    app.jinja_env.globals.update(
        confirm=lambda realm, *args: Confirmation(realm).dumps(tuple(args)))

    app.user_backend = get_backend(app.config['USER_BACKEND'], app)
    app.mail_backend = get_backend(app.config['MAIL_BACKEND'], app)

    return app

accounts/backend/user/__init__.py
# -*- coding: utf-8 -*-


class NoSuchUserError(ValueError):
    pass


class InvalidPasswordError(ValueError):
    pass


class ShouldNotHappen(RuntimeError):
    pass


class Backend(object):
    """
    This is the backend class for the account management. It is
    stateless, so every request needs the authentication data again.

    * register a new user
      >> backend = Backend(app)
      >> foo = Account('foo','foo@bar.de', password='bar')
      >> backend.register(foo)

    * authenticate a new user
      >> backend = Backend(app)
      >> foo = backend.auth('foo', 'bar')

    * updates an account
      >> foo.change_mail('a@b.de')
      >> foo.change_password('newpw','oldpw')           # changes root password
      >> foo.change_password('newpw','oldpw', 'gitlab') # changes password for gitlab
      >> backend.update(foo)                            # save changes in the backend
      # save changes in the backend as admin user (no need for old password)
      >> backend.update(foo, as_admin=True)

    * delete an account
      >> backend = Backend(app)
      >> backend.delete(Account)

    * find accounts
      >> backend = Backend(app)
      >> all_accounts = backend.find()         # find all accounts
      >> print([x.uid for x in all_accounts])
      >> backend.find_by_uid('test')           # find users by uid
      >> backend.get_by_uid('test')            # same, raise NoSuchUserError if no match
      >> backend.find_by_mail('test@test.de')  # find users by mail
      >> backend.find_by_uid('test*', wildcard=True) # find with wildcards
    """

    def __init__(self, app):
        self.app = app

        #: Exception type, that is raised if no matching user was found.
        self.NoSuchUserError = NoSuchUserError

        #: Exception type, that is raised if you try to authenticate with
        #: wrong password. Because this backend is stateless, this exception
        #: could also be raised, if you want to change user information.
        self.InvalidPasswordError = InvalidPasswordError

    def auth(self, username, password):
        """
        Tries to authenticate a user with a given password. If the
        authentication is successful an Account object will be returned.
        """
        raise NotImplementedError()

    def get_by_uid(self, uid):
        """
        Find a single user by uid. Unlike find_by_uid, don't return a list but
        raise NoSuchUserError if there is no such user.
        """
        users = self.find_by_uid(uid)
        if len(users) == 0:
            raise NoSuchUserError('No such user')
        if len(users) > 1:
            raise ShouldNotHappen('Several users for one uid returned.')

        return users[0]

    def get_by_mail(self, mail):
        """
        Find a single user by mail. Unlike find_by_mail, don't return a list but
        raise NoSuchUserError if there is no such user.
        """
        users = self.find_by_mail(mail)
        if len(users) == 0:
            raise NoSuchUserError('No such user')
        if len(users) > 1:
            raise ShouldNotHappen('Several users for one mail returned.')

        return users[0]

    def find_by_uid(self, uid, wildcard=False):
        return self.find({'uid': uid}, wildcard)

    def find_by_mail(self, mail, wildcard=False):
        return self.find({'mail': mail}, wildcard)

    def find(self, filters=None, wildcard=False):
        """
        Find accounts by a given filter.
        """
        raise NotImplementedError()

    def register(self, account):
        """
        Register a new user account.

        This message checks the given account for plausibility,
        get a new uidNumber and store the account into the backend.
        """
        if account.password is None:
            raise ValueError("Password required for register")

        account.uidNumber = self._get_next_uidNumber()
        self._store(account)

    def update(self, account, as_admin=False):
        """
        Updates account information like passwords or email.
        """
        raise NotImplementedError()

    def delete(self, account, as_admin=False):
        """
        Deletes an account permanently.
        """
        raise NotImplementedError()

    def _store(self, account):
        """
        Persists an account in the backend.
        """
        raise NotImplementedError()

    def _get_next_uidNumber(self):
        """
        Get the next free uid number.

        During registration the backend need to assign a unique
        uidNumber for each user. Most backends are unable to
        automaticall increment a value. So this method is used by
        register() to get the next free uid number in a safe way.
        """
        raise NotImplementedError()

accounts/utils/__init__.py
# -*- coding: utf-8 -*-
import importlib
from functools import wraps
from flask import render_template, request
from wtforms.validators import Regexp, ValidationError


# using http://flask.pocoo.org/docs/patterns/viewdecorators/
def templated(template=None):
    def templated_(f):
        @wraps(f)
        def templated__(*args, **kwargs):
            template_name = template
            if template_name is None:
                template_name = request.endpoint \
                    .replace('.', '/') + '.html'
            ctx = f(*args, **kwargs)
            if ctx is None:
                ctx = {}
            elif not isinstance(ctx, dict):
                return ctx
            return render_template(template_name, **ctx)
        return templated__
    return templated_


def ensure_utf8(s):
    if isinstance(s, unicode):
        s = s.encode('utf8')
    return s


class NotRegexp(Regexp):
    """
    Like wtforms.validators.Regexp, but rejects data that DOES match the regex.
    """
    def __call__(self, form, field):
        if self.regex.match(field.data or u''):
            if self.message is None:
                self.message = field.gettext(u'Invalid input.')

            raise ValidationError(self.message)


def get_backend(path, app):
    module = path.rsplit(".", 1).pop()
    class_name = '%sBackend' % module.title()
    backend_class = getattr(importlib.import_module(path), class_name)
    return backend_class(app)

accounts/views/default/__init__.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import

from copy import deepcopy
from flask import Blueprint
from flask import current_app, redirect, render_template, request, g, \
     flash, url_for
from flask.ext.login import login_required, login_user, logout_user, current_user
from werkzeug.exceptions import Forbidden

from accounts.forms import RegisterForm, RegisterCompleteForm, \
    LostPasswordForm, SettingsForm
from accounts.utils import templated
from accounts.utils.confirmation import Confirmation
from accounts.utils.login import logout_required
from accounts.models import Account


bp = Blueprint('default', __name__)


@bp.route('/register', methods=['GET', 'POST'])
@templated('register.html')
@logout_required
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        current_app.mail_backend.send(form.mail.data, 'mail/register.txt',
                                      username=form.username.data)

        flash(u'Es wurde eine E-Mail an die angegebene Adresse geschickt, '
              u'um diese zu überprüfen. Bitte folge den Anweisungen in der '
              u'E-Mail.', 'success')

        return redirect(url_for('.index'))

    return {'form': form}


@bp.route('/register/<token>', methods=['GET', 'POST'])
@templated('register_complete.html')
@logout_required
def register_complete(token):
    #TODO: check for double uids and mail
    username, mail = Confirmation('register').loads_http(token, max_age=3*24*60*60)

    try:
        current_app.user_backend.get_by_uid(username)
        current_app.user_backend.get_by_mail(mail)
    except current_app.user_backend.NoSuchUserError:
        pass
    else:
        flash(u'Du hast den Benutzer bereits angelegt! Du kannst dich jetzt einfach einloggen:')
        return redirect(url_for('.index'))

    form = RegisterCompleteForm()
    if form.validate_on_submit():
        user = Account(username, mail, password=form.password.data)
        current_app.user_backend.register(user)
        login_user(user)

        current_app.mail_backend.send(
            current_app.config['MAIL_REGISTER_NOTIFY'],
            'mail/register_notify.txt',
            username=username, mail=mail)

        flash(u'Benutzer erfolgreich angelegt.', 'success')
        return redirect(url_for('.index'))

    return {
        'form': form,
        'token': token,
        'username': username,
        'mail': mail,
    }


@bp.route('/lost_password', methods=['GET', 'POST'])
@templated('lost_password.html')
@logout_required
def lost_password():
    form = LostPasswordForm()
    if form.validate_on_submit():
        #TODO: make the link only usable once (e.g include a hash of the old pw)
        # atm the only thing we do is make the link valid for only little time
        current_app.mail_backend.send(
            form.user.mail, 'mail/lost_password.txt', username=form.user.uid)

        flash(u'Wir haben dir eine E-Mail mit einem Link zum Passwort ändern '
              u'geschickt. Bitte folge den Anweisungen in der E-Mail.', 'success')

        return redirect(url_for('.index'))

    return {'form': form}


@bp.route('/lost_password/<token>', methods=['GET', 'POST'])
@templated('lost_password_complete.html')
@logout_required
def lost_password_complete(token):
    (username,) = Confirmation('lost_password').loads_http(token, max_age=4*60*60)

    form = RegisterCompleteForm()
    if form.validate_on_submit():
        user = current_app.user_backend.get_by_uid(username)
        user.change_password(form.password.data)
        current_app.user_backend.update(user, as_admin=True)
        login_user(user)

        flash(u'Passwort geändert.', 'success')
        return redirect(url_for('.index'))

    return {
        'form': form,
        'token': token,
        'username': username,
    }


@bp.route('/', methods=['GET', 'POST'])
@templated('index.html')
@login_required
def index():
    form = SettingsForm(mail=current_user.mail)
    if form.validate_on_submit():
        changed = False

        if request.form.get('submit_services'):
            for service in current_app.all_services:
                field = form.get_servicedelete(service.id)
                if field.data:
                    current_user.reset_password(service.id)
                    changed = True

        elif request.form.get('submit_main'):
            if form.mail.data and form.mail.data != current_user.mail:
                current_app.mail_backend.send(
                    form.mail.data, 'mail/change_mail.txt',
                    username=current_user.uid)

                flash(u'Es wurde eine E-Mail an die angegebene Adresse geschickt, '
                      u'um diese zu überprüfen. Bitte folge den Anweisungen in der '
                      u'E-Mail.', 'success')
                changed = True

            if form.password.data:
                current_user.change_password(form.password.data, form.old_password.data)
                flash(u'Passwort geändert', 'success')
                changed = True

            for service in current_app.all_services:
                field = form.get_servicepassword(service.id)
                if field.data:
                    changed = True
                    current_user.change_password(field.data, None, service.id)

        if changed:
            current_app.user_backend.update(current_user)
            login_user(current_user)
            return redirect(url_for('.index'))
        else:
            flash(u'Nichts geändert.')


    services = deepcopy(current_app.all_services)
    for s in services:
        s.changed = s.id in current_user.services

    return {
        'form': form,
        'services': services,
    }


@bp.route('/change_mail/<token>')
@login_required
def change_mail(token):
    username, mail = Confirmation('change_mail').loads_http(token, max_age=3*24*60*60)

    if current_user.uid != username:
        raise Forbidden(u'Bitte logge dich als der Benutzer ein, dessen E-Mail-Adresse du ändern willst.')

    results = current_app.user_backend.find_by_mail(mail)
    for user in results:
        if user.uid != current_user.uid:
            raise Forbidden(u'Diese E-Mail-Adresse wird schon von einem anderen account benutzt!')

    current_user.change_email(mail)
    current_app.user_backend.update(current_user)

    flash(u'E-Mail-Adresse geändert.', 'success')
    return redirect(url_for('.index'))


@bp.route('/about')
@templated('about.html')
def about():
    return {
        'app': current_app,
    }


@bp.app_errorhandler(403)
@bp.app_errorhandler(404)
@bp.app_errorhandler(Exception)
def errorhandler(e):
    try:
        code = e.code
    except AttributeError:
        code = 500

    return render_template('error.html', error=e), code

accounts/views/login/__init__.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import

from flask import Blueprint
from flask import current_app, redirect, request, g, flash, render_template, url_for
from flask.ext.login import login_user, logout_user, current_user
from urlparse import urljoin, urlparse

from .forms import LoginForm


bp = Blueprint('login', __name__)


def is_safe_url(target):
    ref_url = urlparse(request.host_url)
    test_url = urlparse(urljoin(request.host_url, target))
    print(target)
    print(test_url)
    return test_url.scheme in ('http', 'https') and \
           ref_url.netloc == test_url.netloc and \
           test_url.path == target


@bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated():
        return redirect(url_for('default.index'))

    form = LoginForm(request.form)
    if form.validate_on_submit():
        try:
            user = current_app.user_backend.auth(form.username.data,
                                                 form.password.data)
            login_user(user)
            flash(u'Erfolgreich eingeloggt', 'success')

            next = request.form['next']
            if not is_safe_url(next):
                next = None
            return redirect(next or url_for('default.index'))
        except (current_app.user_backend.NoSuchUserError,
                current_app.user_backend.InvalidPasswordError):
            flash(u'Ungültiger Benutzername und/oder Passwort', 'error')

    return render_template("login/login.html", form=form,
                           next=request.values.get('next'))


@bp.route('/logout')
def logout():
    logout_user()
    flash(u'Erfolgreich ausgeloggt.', 'success')
    return redirect(url_for('.login'))

accounts/templates/_macros.html
{% macro render_submit() %}
<div class="control-group">
  <div class="controls">
    <input type="submit"
    {%- for key, value in kwargs.items() %}
      {{key}}="{{value}}"
    {% endfor %}
    />
  </div>
</div>
{%- endmacro %}

{% macro render_field(field) %}
  {% if field.type in ['HiddenField', 'CSRFTokenField'] %}
    {{ field()|safe }}
  {% else %}
<div class="control-group">
  {{ field.label }}
  <div class="controls">
    {{ field(**kwargs)|safe }}
    {{ render_errors(field.errors) }}
  </div>
</div>
{% endif %}
{%- endmacro %}

{% macro render_errors(errors) %}
  {%- if errors|length == 1 %}
  <div class="errors">
    {{ errors.0 }}
  </div>
  {% elif errors %}
  <ul class="errors">
  {% for error in errors %}
    <li>{{ error }}</li>
  {% endfor %}
  </ul>
  {% endif %}
{%- endmacro %}

accounts/templates/about.html
{%- extends 'base.html' %}
{%- from '_macros.html' import render_field %}
{%- set title = 'Über spline accounts' %}
{%- block content %}
<h2>Was ist ein Spline-Account?</h2>
<p>
  Mit einem Spline-Account soll man sich in Zukunft bei allen
  <a href="http://spline.de/">Spline-Diensten</a> einloggen können, statt
  sich – wie bisher – bei jedem Dienst neu zu registrieren. (Es sind aber
  noch nicht alle Dienste integriert.)
</p>
<p>
  Das heißt: Du registrierst dich ein Mal hier auf der Seite, und kannst
  dich dann mit diesem Benutzernamen und Passwort bei allen Diensten
  einloggen. In Zukunft wird es sogar möglich sein, für jeden Dienst ein
  abweichendes Passwort zu definieren.
</p>
<h2>Was bedeutet „Dieser Benutzername ist momentan nicht erlaubt“?</h2>
<p>
  Wir sind gerade noch in der Migrationsphase. Da wir noch kein
  automatisiertes System haben, um alte Accounts aus den Diensten zu einem
  Spline-Account zu übertragen, sperren wir vorerst alle Benutzernamen, die
  es schon in einem der Dienste gibt. So haben die Besitzer dieser Accounts
  die Möglichkeit, ihren Benutzernamen zu behalten.
</p>
<p>
  Wenn du schon einen Benutzernamen in einem der alten Dienste hast, kannst
  du uns <a href="mailto:accounts@spline.de">Bescheid sagen</a>, dann
  erstellen wir dir von Hand einen Account.
</p>
<h2>Wie kann ich einen Spline-Account löschen?</h2>
<p>
  Zur Zeit können wir Accounts nur deaktivieren, da gewisse Dienste sonst mit
  den inkonsistenten Daten nicht umgehen können. Wenn du deinen Account
  deaktivieren willst, dann teile uns das am besten per
  <a href="mailto:accounts@spline.de">Mail</a> mit!
</p>
<h2>Welche Dienste sind bisher dabei?</h2>
<ul>
{%- for service in app.all_services %}
  <li><a href="{{ service.url}}">{{ service.name }}</a></li>
{%- endfor %}
</ul>
{%- endblock %}

accounts/templates/base.html
{%- set styles = ['layout.css', 'bootstrap-form.css'] + styles|default([]) %}
{%- set scripts = ['script.js', 'jquery-1.8.2.min.js'] + scripts|default([]) %}
<!doctype html> <html>
  <head>
    <meta charset="utf-8" />
    <title>{% if title %}{{ title }} – {% endif %}spline accounts</title>
    {%- for script in scripts %}
      <script type="text/javascript" src="{{ url_for('static', filename=script) }}"></script>
    {%- endfor %}
    {%- for style in styles %}
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename=style, version='0.2') }}">
    {%- endfor %}
  </head>
  <body>

    <div id="header-background">&nbsp;</div>
    <header>
      <h1>
        <a href="{{ url_for('default.index') }}">
          <img src="{{ url_for('static', filename='logo.png') }}" alt="spline accounts" />
        </a>
      </h1>
      <span id="roundcornerb">&nbsp;</span>
      <span id="roundcornerw">&nbsp;</span>

      <nav id="mainnav">
        <ul>
          <li><a href="http://spline.de">spline.de</a></li>
          <li><a href="{{ url_for('default.about') }}">FAQ</a></li>
        </ul>
      </nav>

      {%- if not no_login_message %}
      <nav id="usermenu">
        <ul>
          {%- if current_user.is_authenticated() %}
          <li>Angemeldet als <strong>{{ current_user.uid }}</strong></li>
            {%- if current_user.uid in config.get('ADMIN_USERS', []) %}
          <li><a href="{{ url_for('admin.index') }}">Admin</a></li>
            {%- endif %}
          <li><a href="{{ url_for('login.logout') }}">Abmelden</a></li>
          {%- else %}
          <li>Nicht angemeldet</li>
          <li><a href="{{ url_for('login.login') }}">Login</a></li>
          {%- endif %}
        </ul>
      </nav>
      {%- endif %}
    </header>

    <section id="content">
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      <ul class="flashes">
      {% for category, message in messages %}
        <li class="{{ category }}">{{ message }}</li>
      {% endfor %}
      </ul>
      {% endif %}
      {% endwith %}

      {% if title %}
      <h1>{{ title }}</h1>
      {% endif %}
      {% block content %}{% endblock %}
    </section>

    {%- if self.javascript() %}
    <script type="text/javascript">
    {%- block javascript %}{% endblock -%}
    </script>
    {%- endif %}
  </body>
</html>

accounts/templates/error.html
{%- extends 'base.html' %}
{%- from '_macros.html' import render_field %}
{%- block content %}

<h1>Fehler: {{ error.message }}</h1>
{{ error.description|safe }}

{%- endblock %}

accounts/templates/index.html
{%- extends 'base.html' %}
{%- from '_macros.html' import render_field, render_submit %}
{%- set title = 'Einstellungen' %}
{%- block content %}
<form action="{{ url_for('.index') }}" method="post" class="form-horizontal">
  <h2>Globale Einstellungen ändern</h2>
  {{ render_field(form.mail) }}
  <p></p>
  {{ render_field(form.old_password) }}
  {{ render_field(form.password) }}
  {{ render_field(form.password_confirm) }}
  {{ render_field(form.csrf_token) }}
  {{ render_submit(value='Speichern',name='submit_main') }}

  <h2>Dienste verwalten</h2>
  <p>
    Standardmäßig kannst du dich auf allen teilnehmenden Diensten mit dem
    oben konfigurierten allgemeinen Passwort einloggen.
  </p>
  <p>
    Du kannst für jeden Dienst ein eigenes Passwort setzen. Das empfiehlt
    sich zum Beispiel, wenn du einen der Dienste oft unterwegs an fremden
    Rechnern nutzt.
  </p>

  {%- for service in services %}
  <div class="service">
    <h3>
      {% if service.changed %}
        {{ form.get_servicedelete(service.id) }}
      {% else %}
        {{ form.get_servicedelete(service.id)(disabled=True) }}
      {% endif %}
      {{ service.name }}
    </h3>

    <ul>
      {%- if service.changed %}
      <li class="active">eigenes Passwort</li>
      </li>
      {%- else %}
      <li class="inactive">allgemeines Passwort</li>
      {%- endif %}
    </ul>

    <div class="form-service">
      <p>Neues Passwort setzen:</p>
      {{ render_field(form.get_servicepassword(service.id)) }}
      {{ render_field(form.get_servicepasswordconfirm(service.id)) }}
      {{ render_submit(value='Speichern',name='submit_main') }}
    </div>
  </div>
  {%- endfor %}
  <div class="form-submit-services">
    <input type="submit" value="selektierte Passwörter zurücksetzen" name="submit_services" />
  </div>
</form>
{%- endblock %}

{% block javascript %}
  $(document).ready(settings_service_toggle);
{% endblock %}

accounts/templates/lost_password.html
{%- extends 'base.html' %}
{%- from '_macros.html' import render_field, render_submit %}
{%- set title = 'Passwort vergessen' %}
{%- set no_login_message = true %}
{%- block content %}
<p>
  Du hast dein Passwort und/oder deinen Benutzernamen vergessen? Kein Problem.
  Gib einfach unten deinen Benutzernamen bzw. E-Mail-Adresse ein, und wir
  schicken dir einen Link, mit dem du dir ein neues setzen kannst.
  In dieser Mail steht dann auch dein Benutzername.
</p>

<form action="{{ url_for('.lost_password') }}" method="post" class="form-horizontal">
  {% for field in form %}
    {{ render_field(field) }}
  {% endfor %}
  {{ render_submit(value='Weiter')}}
</form>
{%- endblock %}

accounts/templates/lost_password_complete.html
{%- extends 'base.html' %}
{%- from '_macros.html' import render_field, render_submit %}
{%- set title = 'Passwort vergessen' %}
{%- set no_login_message = true %}
{%- block content %}
<p>
  Hier kannst du jetzt ein neues Passwort setzen.
</p>
<form action="{{ url_for('.lost_password_complete', token=token) }}" method="post" class="form-horizontal">
  <div class="control-group">
    <div class="control-label">Benutzername</div>
    <div class="controls"><input readonly="readonly" value="{{ username }}" /></div>
  </div>
  {% for field in form %}
    {{ render_field(field) }}
  {% endfor %}
  {{ render_submit(value='Speichern')}}
</form>
{%- endblock %}

accounts/templates/register.html
{%- extends 'base.html' %}
{%- from '_macros.html' import render_field, render_submit %}
{%- set title = 'Account erstellen' %}
{%- set no_login_message = true %}
{%- block content %}
<p>Hier kannst du dir einen Spline-Account erstellen.</p>
<p>
  Da der Benutzername von möglichst vielen Diensten verarbeitet werden
  können soll, sind nur normale Buchstaben (keine Umlaute), Zahlen und
  Bindestriche  erlaubt (beim ersten Zeichen nur Buchstaben).
</p>
<p>
  Bitte such dir deinen Benutzernamen gut aus. Er kann später nicht mehr
  geändert werden.
</p>
<form action="{{ url_for('.register') }}" method="post" class="form-horizontal">
  {% for field in form %}
    {{ render_field(field) }}
  {% endfor %}
  {{ render_submit(value='E-Mail-Adresse bestätigen')}}
</form>
{%- endblock %}

accounts/templates/register_complete.html
{%- extends 'base.html' %}
{%- from '_macros.html' import render_field, render_submit %}
{%- set title = 'Account erstellen' %}
{%- set no_login_message = true %}
{%- block content %}
<p>
  Deine E-Mail-Adresse wurde erfolgreich bestätigt.
  Bitte setze nun ein Passwort, um die Registrierung abzuschließen.
</p>
<form action="{{ url_for('.register_complete', token=token) }}" method="post" class="form-horizontal">
  <div class="control-group">
    <div class="control-label">Benutzername</div>
    <div class="controls"><input readonly="readonly" value="{{ username }}" /></div>
  </div>
  <div class="control-group">
    <div class="control-label">E-Mail-Adresse</div>
    <div class="controls"><input readonly="readonly" value="{{ mail }}" /></div>
  </div>
  {% for field in form %}
    {{ render_field(field) }}
  {% endfor %}
  {{ render_submit(value='Registrieren')}}
</form>
{%- endblock %}